name: TheNeedfuls
version: 0.2
author: Selurgniman
main: org.selurgniman.bukkit.theneedfuls.TheNeedfuls

database: false

commands:
    tnh:
        description: Get help with TheNeedfuls.
        permission: theneedfuls.help
        usage:  |
            /<command> [torch|ice|xp|ohnoez|help]
    tnt:
        description: Set TheNeedfuls torch options.
        permission: theneedfuls.torch
        usage:  |
            /<command> [age|refresh|count|expire|worlds] [options]
            Example: /<command> age 300 - set the maximum torch age to 300 seconds.
            Example: /<command> refresh 30 - set the torch expiration check to every 30 seconds.
            Example: /<command> count - see how many torches are being tracked.
            Example: /<command> expire - expire all torches being tracked.
            Example: /<command> worlds - see a list of worlds that torch expiration is enabled on.
            Example: /<command> worlds add world - enable torch expiration on world named "world".
            Example: /<command> worlds remove world - disable torch expiration on world named "world".
    tni:
        description: Set TheNeedfuls ice options.
        permission: theneedfuls.ice
        usage:  |
            /<command> [quantity] [1-64]
            Example: /<command> quantity 32 - set the stack size of the dispensed ice to 32.
    tnx:
        description: Set TheNeedfuls experience options.
        permission: theneedfuls.xp
        usage:  |
            /<command> [show|give|take|set] [level integer]
            Example: /<command> show <player> - Show the player's level.
            Example: /<command> give <player> 5 - add 5 levels to the player.
            Example: /<command> take <player> 5 - remove 5 levels from the player.
            Example: /<command> set <player> 5 - set the player's level to 5.
    ohnoez:
        description: Set TheNeedfuls ohnoez options.
        permission: theneedfuls.ohnoez
        usage:  |
            /<command> [list|credits|claim|world] [level integer]
            Example: /<command> list - Show the player's last death inventory.
            Example: /<command> credits - Show the players available credits.
            Example: /<command> credits add <player> 1 - add 1 credit for the player.
            Example: /<command> credits set <player> 0 - set the player's credits to 0.
            Example: /<command> claim - use an available credit and get your drops back.
            Example: /<command> worlds - see a list of worlds that death inventory tracking is enabled on.
            Example: /<command> worlds add world - enable death inventory tracking on world named "world".
            Example: /<command> worlds remove world - disable death inventory tracking on world named "world".

permissions:
    theneedfuls.*:
        description: Gives access to all TheNeedfuls commands.
        default: op
        children:
        	theneedfuls.help.*: true
            theneedfuls.torch.*: true
            theneedfuls.ice.*: true
            theneedfuls.xp.*: true
            theneedfuls.ohnoez.*: true
    theneedfuls.help.*:
        description: Gives access to all TheNeedfuls help commands.
        default: true
        children:
            theneedfuls.help.help: true
            theneedfuls.help.torch: true
            theneedfuls.help.ice: true
            theneedfuls.help.xp: true
            theneedfuls.help.ohnoez: true
    theneedfuls.torch.*:
        description: Gives access to all TheNeedfuls torch commands.
        default: op
        children:
            theneedfuls.torch.age: true
            theneedfuls.torch.refresh: true
            theneedfuls.torch.count: true
            theneedfuls.torch.expire: true
            theneedfuls.torch.worlds: true
    theneedfuls.ice.*:
        description: Gives access to all TheNeedfuls ice commands.
        default: op
        children:
            theneedfuls.ice.quantity: true
    theneedfuls.xp.*:
        description: Gives access to all TheNeedfuls experience commands.
        default: op
        children:
            theneedfuls.xp.show: true
            theneedfuls.xp.give: true
            theneedfuls.xp.take: true
            theneedfuls.xp.set: true
    theneedfuls.ohnoez.*:
        description: Gives access to all TheNeedfuls ohnoez commands.
        default: op
        children:
            theneedfuls.ohnoez.list: true
            theneedfuls.ohnoez.credits.*: true
            theneedfuls.ohnoez.claim: true
            theneedfuls.ohnoez.worlds: true
    theneedfuls.help.help:
        description: Allows you to see help for help.
        default: true
    theneedfuls.help.torch:
        description: Allows you to see help for torch.
        default: true
    theneedfuls.help.ice:
        description: Allows you to see help for ice.
        default: true
    theneedfuls.help.xp:
        description: Allows you to see help for xp.
        default: true
    theneedfuls.help.ohnoez:
        description: Allows you to see help for ohnoez.
        default: true
    theneedfuls.torch.age:
        description: Allows you to set the maximum age for torches.
        default: op
    theneedfuls.torch.refresh:
        description: Allows you to set the torch expiration check frequency.
        default: op
    theneedfuls.torch.count:
        description: Allows you to list the number of torches being tracked.
        default: true
    theneedfuls.torch.expire:
        description: Allows you to expire all of the torches being tracked.
        default: op
    theneedfuls.torch.worlds:
        description: Allows you to set the worlds which torch expiration is enabled.
        default: op
    theneedfuls.ice.quantity:
        description: Allows you to set the stack size for the ice being dispensed.
        default: op
    theneedfuls.xp.show:
        description: Allows you to see a player's experience level.
        default: true
    theneedfuls.xp.give:
        description: Allows you to give a player experience levels.
        default: op
    theneedfuls.xp.take:
        description: Allows you to take experience levels from a player.
        default: op
    theneedfuls.xp.set:
        description: Allows you to set another player's experience level.
        default: op
    theneedfuls.ohnoez.list:
        description: Allows you to list your last store death inventory.
        default: yes
    theneedfuls.ohnoez.credits.*:
        description: Gives access to all TheNeedfuls ohnoez credit commands.
        default: op
        children:
            theneedfuls.ohnoez.credits.show: true
            theneedfuls.ohnoez.credits.add: true
            theneedfuls.ohnoez.credits.set: true
    theneedfuls.ohnoez.credits.show:
        description: Allows you to display the available credits.
        default: yes
    theneedfuls.ohnoez.credits.add:
        description: Allows you to add available credits.
        default: op
    theneedfuls.ohnoez.credits.set:
        description: Allows you to set available credits.
        default: op
    theneedfuls.ohnoez.claim:
        description: Allows you to claim an available credit.
        default: true
    theneedfuls.ohnoez.worlds:
        description: Allows you to set the worlds which death inventory tracking is enabled.
        default: op